### ISSUE TITLE
Replay voicechat requires older version of replay mod on 1.20.1

### ISSUE THREAD

**Issue by netcore10** [henkelmax/replay-voice-chat#25] opened 2023-12-18 21:35 UTC
Dependencies are out of date.

![image](https://github.com/henkelmax/replay-voice-chat/assets/181536/286bd800-8652-41da-a3b5-73adcb8a3689)

**Comment by henkelmax** [comment] 2023-12-18 22:05
Duplicate of #24

**Closed by henkelmax** 2023-12-18 22:05 UTC
Labels: triage
